### ISSUE TITLE
Error: spawn vite ENOENT

### ISSUE THREAD

**Issue by ghost** [ATQQ/webpack-vite-serve#3]
Hello, I installed your command and reported an error after execution:
![image](https://user-images.githubusercontent.com/10797575/141423171-4c25a68e-4448-4ba0-9126-45b68d40884b.png)

**Comment by ATQQ** [comment]
when use Soft link in project，will Cause this problem

![image](https://user-images.githubusercontent.com/42485491/141477134-b2907ad9-e9e4-4b02-b24b-aed1b0bc1fa9.png)

Direct installation of dependencies can solve this problem

>please remember delete lock file，then installed it
```sh
npm install webpack-vite-serve -D
# or
yarn add webpack-vite-serve -D
# or
pnpm add webpack-vite-serve -D
```

![image](https://user-images.githubusercontent.com/42485491/141477416-f7382e60-cde9-477f-a5ce-73f720a3d747.png)

**Comment by ATQQ** [comment]
this pr solve it https://github.com/ATQQ/webpack-vite-serve/pull/4
